### ISSUE TITLE
Susi not able to display the map tile after repeated query.

### ISSUE THREAD

**Issue by daminisatya** [fossasia/asksusi.com#19]
**Reproduce the steps:** 
- Type in the query `Where is Singapore?`
- You will get a map tile something like this....
  ![selection_310](https://cloud.githubusercontent.com/assets/6227784/17835320/5eb8920e-6785-11e6-8724-41386509afeb.png)
- Type in the same query  `Where is Singapore?`
- Expected : You must see the same map tile. But for some reason the tile is not able to get the display. 
  ![selection_312](https://cloud.githubusercontent.com/assets/6227784/17835326/8f939dd8-6785-11e6-867a-7d89f122bb10.png)

**Comment by SpEcHiDe** [comment]
This seems to be an error with the leaflet.js dependency. Can I be assigned this issue?

**Comment by daminisatya** [comment]
@SpEcHiDe Yes, the problem is with the leaflet.js, cause they are aiming at caching the details.The console throws an error saying that the map object is already being initialized.

**Comment by SpEcHiDe** [comment]
I think I figured out the problem. An element should have an unique ID. but, the ID being created by the index.js#L152 file is map-{lat}-{lng} 
The problem can be solved by appending a timestamp of the message sent time (or some other unique ID) in the element ID.

**Comment by SpEcHiDe** [comment]
@daminisatya  Isn't this issue fixed in #33 ?

**Comment by KukkadapuSushma** [comment]
i would like to work on this @daminisatya , Please do add me!

**Comment by daminisatya** [comment]
@KukkadapuSushma please verify if this issue is still persisting, else close it

**Comment by smokingwheels** [comment]
Hi @daminisatya You might find [This useful](https://github.com/smokingwheels/shaper)

**Comment by jig08** [comment]
Un-assigning this due to inactivity, feel free to take this up. Thanks !

**Comment by SpEcHiDe** [comment]
@jig08 Isn't this issue fixed in #33 ?

**Comment by jig08** [comment]
@SpEcHiDe Thanks for pointing that out, the issue wasn't referenced hence the misunderstanding. Closing this ....
