### ISSUE TITLE
Responsive UI for asksusi

### ISSUE THREAD

**Issue by daminisatya** [fossasia/asksusi.com#20]
Currently the css is not mobile compatible. 
![screenshot_2016-08-21-10-17-34_com android chrome](https://cloud.githubusercontent.com/assets/6227784/17835584/eff20646-6790-11e6-832f-24a93cfce11a.png)

The css needs to be tested on various devices and make use of bootstrap.

**Comment by PrabhanshuAttri** [comment]
How about material design?

**Comment by daminisatya** [comment]
@PrabhanshuAttri Can you be more clear

**Comment by PrabhanshuAttri** [comment]
I was thinking about UI similar to these (I would prefer the first one).
![800x600](https://cloud.githubusercontent.com/assets/4739486/20546393/d3587670-b13a-11e6-88bd-10467c18b006.png)

![mat 1](https://cloud.githubusercontent.com/assets/4739486/20546396/db6cb542-b13a-11e6-8776-3f70a5b0adc3.png)

![preview](https://cloud.githubusercontent.com/assets/4739486/20546401/df99c7fe-b13a-11e6-9959-a543f6fdd9eb.jpg)

I think developing our own design language (similar to existing ones) is better than using other chat UIs. @mariobehling @Orbiter What do you guys think about it?

**Comment by mariobehling** [comment]
@daminisatya Looks good.

Can we start with the first design? Please also use the top bar from the second design.

**Comment by daminisatya** [comment]
@mariobehling @PrabhanshuAttri Cool, should take this forward with angular. I can help out with this.

**Comment by PrabhanshuAttri** [comment]
@mariobehling Cool, I will get started. @daminisatya Let me make the first design. There is this problem with angular that it makes SEO hard and I think we really need SEO. I will figure something out and will let you know.

**Comment by mariobehling** [comment]
@PrabhanshuAttri Don't worry so much about this at this stage. We need to integrate the chat app with the accounting, that is already in Angular. So this issue needs to be aligned with https://github.com/fossasia/asksusi.com/issues/30

**Comment by PrabhanshuAttri** [comment]
@mariobehling Cool. Just a few questions. Does node + angular works? Also, where can I find the code of api.asksusi.com (accounting).

**Comment by mariobehling** [comment]
@PrabhanshuAttri 

> Does node + angular work? 

Yes.

> Also, where can I find the code of api.asksusi.com (accounting).

https://github.com/fossasia/susi_server

**Comment by mariobehling** [comment]
@PrabhanshuAttri On a second thought. Actually nodejs cannot run easily on Github pages and we would need to set up deployment to Heroku for testing. If Node is absolutely required then go ahead. Otherwise, stick with Angular, please. Cheers.

**Comment by PrabhanshuAttri** [comment]
I guess Heroku deployment won't be an issue. Almost done with the design, will develop and send PR by end of the week. Cheers.

**Comment by PrabhanshuAttri** [comment]
@mariobehling Shall do this in angular? I was engaged in some urgent work. I am done with the design.
