### ISSUE TITLE
Implement a new start page for asksusi.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/asksusi.com#29]
The idea is to make the start page of http://asksusi.com into the main gateway for getting the susi Android app. Therefore:

1. Move the current app to http://asksusi.com/chat/
2. Implement a start page with
    * AngularJS
    * a download link to https://github.com/fossasia/susi_android/raw/apk/susi-debug.apk
    * for the page design get inspiration from sites like twitter: https://twitter.com/download?logged_out=1&lang=en
    * implement a gray top bar (in the same style as http://loklak.fossasia.org)
    * implement the main area with a white background

**Comment by BrainBuzzer** [comment]
This is supposed to be a design part and I don't think so that there is any need of AngularJS here.

**Comment by jig08** [comment]
@BrainBuzzer I believe the task is not to just prepare a mock-up but use the AngularJS framework to implement the design as well :)

**Comment by BrainBuzzer** [comment]
@jig08 I know but a rough picture is required. Adding angularjs would only slow down web page loading time. If you are mentor, would you please see the thread and see this again.

**Comment by BrainBuzzer** [comment]
Using aurelia.io as front end would be quite good if we really are interested in adding a framework.

**Comment by BrainBuzzer** [comment]
Completed. Check out pull request for more info.

**Comment by jig08** [comment]
@mariobehling I suggest we could take inspiration from [allo.google.com](https://allo.google.com/)

**Comment by adityak1121** [comment]
does the navigation bar needs to have the same links as in asksusi.com/chat

> ?
