### ISSUE TITLE
Using Aurelia for the front end

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/asksusi.com#35]
I have created several chat application with the help of this framework. I have used Aurelia in so many frameworks and performance wise it is better than Angular. Should I port entire application to Aurelia? I have already faced so many difficulties during fixing issue #20. @daminisatya @mariobehling @Orbiter please check out quickly.

**Comment by mariobehling** [comment]
@BrainBuzzer There are pros and cons for many frameworks and there is little experience of many developers with Aurelia. So, I think at this point Aurelia is not on the list. Thank you.
